from django.db import models


class Bar(models.Model):
    a1 = models.CharField(blank=True, max_length=255)
    a2 = models.CharField(blank=True, max_length=255)
    a3 = models.CharField(blank=True, max_length=255)
    a4 = models.CharField(blank=True, max_length=255)
    a5 = models.CharField(blank=True, max_length=255)
    a6 = models.CharField(blank=True, max_length=255)
    a7 = models.CharField(blank=True, max_length=255)
    a8 = models.CharField(blank=True, max_length=255)
    a9 = models.CharField(blank=True, max_length=255)
    a10 = models.CharField(blank=True, max_length=255)
    a11 = models.CharField(blank=True, max_length=255)
    a12 = models.CharField(blank=True, max_length=255)
    a13 = models.CharField(blank=True, max_length=255)
    a14 = models.CharField(blank=True, max_length=255)
    a15 = models.CharField(blank=True, max_length=255)
    a16 = models.CharField(blank=True, max_length=255)
    a17 = models.CharField(blank=True, max_length=255)
    a18 = models.CharField(blank=True, max_length=255)
    a19 = models.CharField(blank=True, max_length=255)
    a20 = models.CharField(blank=True, max_length=255)
    a21 = models.CharField(blank=True, max_length=255)
    a22 = models.CharField(blank=True, max_length=255)
    a23 = models.CharField(blank=True, max_length=255)
    a24 = models.CharField(blank=True, max_length=255)
    a25 = models.CharField(blank=True, max_length=255)
    a26 = models.CharField(blank=True, max_length=255)
    a27 = models.CharField(blank=True, max_length=255)
    a28 = models.CharField(blank=True, max_length=255)
    a29 = models.CharField(blank=True, max_length=255)
    a30 = models.CharField(blank=True, max_length=255)
    a31 = models.CharField(blank=True, max_length=255)
    a32 = models.CharField(blank=True, max_length=255)
